### ISSUE TITLE
Java MatrixFactorizationModel Save / Load Error

### ISSUE THREAD

**Issue by StephenCathcart** [tomncooper/CSC8101-Documentation#6]
Hi,

I'm currently using Java for the coursework and I've used the Java spark batch project template provided (which includes a pom file).

I'm receiving the following error after trying to save / load the MatrixFactorizationModel object. All other mllib functions are working correctly (such as ALS train):

```
MatrixFactorizationModel model = ALS.train(...);
model.save(sc, "path");
```

Error:
```
Exception in thread "main" java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaMirrors$JavaMirror;
        at org.apache.spark.mllib.recommendation.MatrixFactorizationModel$SaveLoadV1_0$.save(MatrixFactorizationModel.scala:190)
        at org.apache.spark.mllib.recommendation.MatrixFactorizationModel.save(MatrixFactorizationModel.scala:139)
        at uk.co.stephencathcart.csc8101.sparkbatch.Main.runTaskTwo(Main.java:126)
        at uk.co.stephencathcart.csc8101.sparkbatch.Main.main(Main.java:43)
```
My guess is the pom dependency versions are incorrect for the version of scala on the VM (2.11.6). The template pom currently includes:
```
<dependency>
	<groupId>org.apache.spark</groupId>
	<artifactId>spark-core_2.11</artifactId>
	<version>2.1.0</version>
</dependency>
<dependency>
	<groupId>org.apache.spark</groupId>
	<artifactId>spark-mllib_2.10</artifactId>
	<version>1.3.0</version>
</dependency>
<dependency>
	<groupId>org.apache.spark</groupId>
	<artifactId>spark-sql_2.10</artifactId>
	<version>2.1.0</version>
</dependency>
```
Adding the scala reflect dependency seems to help a bit but fails later on:
```
<dependency>
	<groupId>org.scala-lang</groupId>
	<artifactId>scala-reflect</artifactId>
	<version>2.10.0</version>
</dependency>
```
New error:
```
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
Do you have any ideas on the correct versions of the spark dependencies to use? I can still progress with the coursework without these features but would speed up development.

Cheers

**Comment by StephenCathcart** [comment]
Updating the spark-mllib from 1.3.0 to 2.1.0 did the trick, not sure why this would be causing the noSuchMethodError but the model is saving / loading correctly now so happy to close the issue.
